/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_5;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
          Scanner sc = new Scanner(System.in);
        System.out.println("VAMOS A CALCULAR EL SUELDO LIQUIDO Y EL SUELDO BRUTO");
        double sueldo = 1000;
        System.out.println("Cuanto vendiste este més?");
        double d_ventas = sc.nextDouble();
        System.out.println("cuantos kilometros te desplazaste?");
        double km = sc.nextDouble();
         System.out.println("Durante cuantos días?");
        double diasDesplazados = sc.nextDouble();
        
        //Calculamos la comisión por el importe total de las ventas
        sueldo += d_ventas * 0.05;
        //Añadimos 2€ por kilometro recorrido
        sueldo += km * 2;
        //Añadimos 30€ por día de desplazamiento
        sueldo += diasDesplazados*30;
        System.out.println("El sueldo bruto es de " + sueldo + "€");
        
        //AHORA CALCULEMOS EL SUELDO LIQUIDO
        sueldo -= sueldo * 0.18;
        sueldo -= 36;
        System.out.println("El sueldo NETO es de " + sueldo + "€");
        
    }
}
