/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_2;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());
        //EJERCICIO PASAR DE CENTIGRADOS A Fahrenheit Y a Kelvin
        Scanner sc = new Scanner(System.in);
        System.out.println("Introduzca la temperatura en Celsius");
        double temp = sc.nextDouble();
        double F = (temp * 9 / 5) + 32;
        double K = temp + 273.15;
        System.out.println("La temperatura en Fahrenheit es de: " + F);
        System.out.println("la temperatura en Kelvin es de: "+K);
       
    }
}
