/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_4;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
         Scanner scan = new Scanner (System.in);
      
        System.out.println("Introduce la cantidad entera de euros:  ");
        int dinero = scan.nextInt();//Pido al usuario el dinero que tiene
        int b100, b20, b5 , m1; //Declaro las variables de todos los billetes
        b100 = dinero/100;
        System.out.println("La cantidad de billetes de 100 es: " + b100);
        b20 = (dinero % 100)/20; 
        System.out.println("La cantidad de billetes de 20 es: " + b20);
        dinero -=b100*100;
        dinero-=b20*20;//Restamos al dinero inicial la suma de los billetes de 100 y de 20
        b5 = (dinero %100 % 20)/ 5;
        System.out.println("La cantidad de billetes de 5 es: " + b5);
        m1 = (dinero % 100 %20%5);
        System.out.println("La cantidad de monedas de 1 es: " + m1);
        
        
        }
}
