/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_4;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Scanner sc = new Scanner(System.in);
        System.out.println("Introduzca el dinero que tiene");
        double dinero = sc.nextDouble();
        
        double b_100 = dinero / 100;
        double resto = b_100 % 100;
        
        double b_20 = dinero / 20;
        double resto20 = b_20 % 20;
        
        double b_5 = dinero / 5;
        double resto5 = b_5 % 5;
        System.out.println(dinero +" € son " + b_100 + " billetes de 100" + resto20 + " billetes de 20" + resto5+" billetes de 5");
        
        //b100 = dinero /100   resto = b100 % 100   resto
        }
}
