/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Boletin3_4;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Scanner sc = new Scanner(System.in);
        System.out.println("Introduzca el dinero que tiene");
        double dinero = sc.nextDouble();
        double d1 = 0;
        double d2=0;
        double d5=0;
        double B_100 = Math.round(dinero /100);
         d1 = B_100 * 100;
         System.out.println("Tienes " + B_100 + " Billetes de 100");
        double B_20 = Math.round((dinero - d1)/20);
         System.out.println("Tienes " + B_20 + " Billetes de 20");
         d2 = B_20*20;
        double B_5 = Math.round((dinero - (d1)-(d2))/5);
         System.out.println("Tienes " + B_5 + "Billetes de 5");
         d5=B_5*5;
        double billetes = B_100 + B_20 + B_5;
        double M_1 = dinero - d1 - d2 - d5 ;
        System.out.println("Tienes " + billetes + " billetes y " + M_1 + " Monedas");
       
        
        //b100 = dinero /100   resto = b100 % 100   resto
        }
}
